#!/usr/bin/env sh

set -e

STAGED_COUNT=$(git diff --cached --numstat | wc -l)

if [ "$STAGED_COUNT" -eq 0 ]; then
  echo "No files staged. Aborting."
  exit 1
fi

CURRENT=$(git rev-parse HEAD)
echo "Current: $CURRENT"

if [ -n "$1" ]; then
  # Target given as argument
  TARGET=$(git rev-parse $1)
  echo " Target: $TARGET ($1)"
else
  # Use fzf to pick a target
  FORMAT="%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset"
  SELECTED=$(git log --color --pretty=format:"$FORMAT" | fzf --layout=reverse --ansi | awk '{print $1;}')
  TARGET=$(git rev-parse $SELECTED)
  echo " Target: $TARGET"
fi

if [ "$CURRENT" = "$TARGET" ]; then
  # Fixup on last commit, rebase not needed
  git commit --amend --no-edit
else
  # Fixup on previous commit, rewrite history
  git commit --fixup $TARGET
  git rebase --interactive --autosquash --autostash $TARGET~1
fi
